### ISSUE TITLE
Do we want to introduce or provide links to while and until syntax?

### ISSUE THREAD

**Issue by PeterBell** [learn-co-curriculum/looping-while-until#18]
Looks to me like we're asking people to use while and until loops, but in the previous class when we introduced loops we didn't provide either of those syntaxes. Is this a deliberate "time for you to guess/google it", were those syntaxes mentioned earlier in the curriculum and/or is this not a problem because people are getting through it? 

Not saying we *should* change this, but wanted a placeholder so we could have a conversation about it . . .

**Comment by AnnJohn** [comment]
@PeterBell in the full-stack track, this lesson- https://github.com/learn-co-curriculum/while-and-until-looping-readme - comes right before. Is that enough, you think, for them to do the lab?

**Comment by PeterBell** [comment]
Doh - I was taking this using the intro to ruby track - let me take it using the full stack flow - that'll be better. Yes - makes much more sense with that intro. Closing issue as it's not a problem. Thanks so much @AnnJohn

**Comment by PeterBell** [comment]
Hi @AnnJohn realized I wanted to reopen this just to ask one question. When someone is doing the prework for learn.co - are they doing the intro to ruby track? If so, is there a way we could add  https://github.com/learn-co-curriculum/while-and-until-looping-readme  to the intro to ruby track just before this? Otherwise they first time they come across this exercise they're not going to know what to do. Thoughts?

**Comment by AnnJohn** [comment]
clsoing this @PeterBell, since we talked about it. But if I missed something, feel free to re-open and comment. Thanks

**Comment by PeterBell** [comment]
Thanks @AnnJohn it is indeed resolved - it was just an issue with undeployed content in the Intro to Ruby track for the instructors cohort. Thanks so much for taking care of all of this!
