### ISSUE TITLE
Message in terminal: You are attempting to open a lesson that is beyond your current lesson. Are you sure you want to continue?

### ISSUE THREAD

**Issue by mnimmz** [learn-co-curriculum/looping-while-until#22]
When I attempt to fork the lesson, I get this message in my terminal: "You are attempting to open a lesson that is beyond your current lesson. Are you sure you want to continue?" This is not the case, as I am going in order with the lessons....
![screen shot 2017-10-05 at 12 05 06 am](https://user-images.githubusercontent.com/18533905/31210556-09c9e166-a961-11e7-8902-4d98915f5cc1.png)

**Comment by curiositypaths** [comment]
Thanks for [contributing](http://help.learn.co/improving-learn) to the [Learn](http://learn.co/) curriculum!

Bear in mind that [raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform. The first place to turn for most issues is the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) feature on [Learn](http://learn.co/). For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

### Reporting bugs 🐛
If you'd like to [report a bug](http://help.learn.co/improving-learn/reporting-bugs/reporting-a-bug) about the [Learn IDE](http://help.learn.co/the-learn-ide), the [lights not working on Learn](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green), or any other issue with the site, please consult the [Learn Help Center](http://help.learn.co/) and/or escalate the issue via [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). If you are unable to access Ask a Question or your track is not supported by the Technical Coaches, please send us a message via the [Intercom](https://user-images.githubusercontent.com/17556281/27602126-b825ff3a-5b3f-11e7-9dcd-0ced7e507bfb.png) widget on any [Help Center](http://help.learn.co/) page.

### Additional information 🖥
We will do our best to respond quickly to all issues, but to expedite the process it would be extremely helpful if you could include the following information:
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

We'll figure out what's up and get back to you ASAP! 💙
