### ISSUE TITLE
Not Forking

### ISSUE THREAD

**Issue by MahmoudAgamy** [learn-co-curriculum/looping-while-until#27]
I solved the lab and the passed the test but the lab didn't fork

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.

You can reach support via support@learn.co.

[Raising issues on GitHub][raise] should be reserved for problems with
the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
