### ISSUE TITLE
Levitation Charm?

### ISSUE THREAD

**Issue by aenbar** [learn-co-curriculum/looping-while-until#3]
In the "USING WHILE AND UNTIL" it says "Guess what? We're still struggling to master that levitation charm! But we are so close...."

Seems like this lab is referring to a previous example (or I guess "Wingardium Levios" is a levitation charm?). Worth clarifying a bit.

**Comment by joshuabamboo** [comment]
@aenbar It is referring to previous examples. There is a group of looping labs that all keep with the levitation theme. Did you see these? Which track you were on? (cc: @SophieDeBenedetto)

**Comment by AnnJohn** [comment]
Iceboxing for now. Think about changing the language of the lab to make it completely standalone and not refer to any other labs
